import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/general/Navbar/NavBar";
import Footer from "@/components/general/Footer/Footer";
import Topbar from "@/components/general/Topbar/Topbar";
import { authUser } from "../../utils/serverHelpers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await authUser();

  
  return (
    <html lang="en">
      <body className='font-IRANSans' dir="rtl">
        <Topbar/>
        <NavBar name={user? user.name! : ''} isLogedIn={user ? true : false} />
        {children}
        <Footer/>
        </body>
    </html>
  );
}
